### ISSUE TITLE
Doesn't work with SLI

### ISSUE THREAD

**Issue by joshbux** [falahati/NVIDIASurroundToggler#1] opened 2015-11-03 06:34 UTC
I just had the one GTX 970 in originally and this tool worked reasonably well. Finally got a case big enough to put my second 970 in and bridged the two and now toggling into surround mode fails because it can't find the setting in NVIDIA control panel, I'm guessing because the setting is now in a screen called "Configure SLI, Surround, Physx" instead of "Configure Surround and Physx".

**Comment by falahati** [comment] 2015-11-03 17:09
Yeah, I know. Well I cant do much about it as I don't have a SLI setup. But if you are willing to help, I can send you an application and tell you what to do. All I need is a number which is the Control ID of tree node ("Configure SLI, Surround, Physx").

**Comment by joshbux** [comment] 2015-11-03 17:10
Sure I'd be happy to help.

Josh

**Comment by ZaLiTHkA** [comment] 2015-11-03 18:30
I'm also running an SLI setup (Win 10 Pro x64, dual 780Ti, triple monitor config), so if you need someone else to collect info from or help test things, I'm also interested in helping. :)

**Comment by falahati** [comment] 2015-11-03 19:09
Thanks guys,
What I need is the AutomationId of the control in nVidia Control Panel.
For finding that you need to download and run "Visual UI Automation Verify" tool (download link bellow) and little patient.
1. Open the nVidia Control Panel
2. Open the "VisualUIAVerify.exe" file
3. In "Visual UI Automation Verify" tool, navigate to [Pane Desktop] -> [Window NVIDIA Control Panel] -> [Pane Select a Task] -> [Tree] -> [Text Configure Surround, ...] as in the image bellow
4. Select this item and from the right side, read the AutomationId of the control. In single card setups, the automation ID is 4100. If this is the problem, this number should be different
VisualUIAVerify: https://onedrive.live.com/redir?resid=526CD4F33278E424!39658&authkey=!ANcKzfkCJeCtATg&ithint=file%2czip
Image: http://i.imgur.com/qSRKRqH.jpg

**Comment by ZaLiTHkA** [comment] 2015-11-03 19:32
Just like your screenshot, `AutomationId` is also `4100` on my system.

Not gonna lie, I have no idea what these properties relate to, but the only one different in my list from your screenshot is `hWnd`, which is `0x20ADC` on my side.

**Comment by joshbux** [comment] 2015-11-03 19:35
I'm at work, I'll double check when I get home

Josh

**Comment by joshbux** [comment] 2015-11-03 19:40
Although I'd the treeId is the same, the problem might stem from the
different surround option layout. Without SLI it's just a check box but
with it I see 4 radio dials. I'll double check after work, but I'm pretty
sure the dials are for 3D surround, 2D surround (which is the one I'd want
to toggle), enable SLI, and disable SLI. It may be that when toggling you
want to apply a saved value for those options, i.e. toggling surround on
would choose the second one and toggling it off would choose the third.

Josh

**Comment by ZaLiTHkA** [comment] 2015-11-03 19:54
@joshbux, good point.. I just noticed the difference now. My first multi-monitor setup with NVidia was a dual 660Ti, I've never had any reason to try Surround with a single card before so I didn't actually realise that.

@falahati, from what I can see with this UI Automation tool, my window has the following values for `AutomationId`:
- "SLI Configuration" group: `1517`
- "Maximise 3D Performance": `1518`
- "Span all displays with Surround": `1864`
  - "Configure": `1865`
- "Activate all displays": `1519`
- "Disable SLI": `1523`

Hope that helps a bit.. :)

![](http://i.imgur.com/0irGQFY.jpg)

http://imgur.com/0irGQFY

**Comment by joshbux** [comment] 2015-11-03 20:16
Yep, I'm putting my money on that as the issue. Of course, when I want to
toggle it off, I wouldn't want to disable SLI altogether, I'd want to
select activate all displays, which it looks like is ghosted when surround
is enabled, so it may need to be a two step process.

@falahati, while we're on the subject, any chance you could make the
override screen and text color customizable in the options? Every time I
toggle I get kind of blinded by 3 completely white screens and I'd like to
be able to change that to a darker color with light text.

Josh

**Comment by falahati** [comment] 2015-11-03 20:34
Thanks for the values and screenshot.
Yeah the root of the problem is the layout changes. Yet with the values you provided, I can rewrite this part easily.
But then I need someone to confirm its functionality afterward.

My problem now is the logic behind it tho. From what I can guess, I need to use the first option for Extended Mode and second one as Surround mode. Tell me if I am wrong. And why the third radio button is disable?

**Comment by joshbux** [comment] 2015-11-03 20:38
I don't actually know what the first option does because I don't have 3D
glasses, but I believe it is to improve performance of 3D. The second is
definitely surround. The third and 4th are both extended, the third just
enables SLI while the 4th separates the cards. My computer is currently
running extended in SLI mode (3rd option). I'm guessing you want to save
that as part of the user's extended configuration.

Josh

**Comment by falahati** [comment] 2015-11-03 20:40
If "Activate all displays" is the correct mode, what does the first option do? One screen only?

@joshbux  Well there are more than one page involved in the process, some of them I cant do much about. So I used the nearest color to them for the ones I control to make them almost invisible. White was that color :) But I try to make it a little darker and see if that would work.

**Comment by ZaLiTHkA** [comment] 2015-11-03 20:40
It's been a while since I actually switched the settings around, so I had to go check in the NVidia thread where I originally asked for help while I was building my current rig ([see here](https://forums.geforce.com/default/topic/764983/pc-components/need-some-multi-gpu-multi-monitor-setup-advice/post/4306277/#4306277)). Anyways, to be difficult (just because it's so much fun), I would prefer to switch between "Maximise 3D performance" and "Span displays with Surround" instead.. O.o

@falahati, when I hover over the disabled option, the description below says:

> This is disabled because all your displays can be activated when "Maximise 3D performance" is selected.

It's "Typical usage scenarios" states:

> - Gaming with multiple displays
> - Using 3D programs that can utilise multiple displays

From what I recall running games with "Maximise 3D performance" uses only one monitor, while Windows desktop still uses all three, not sure about the 3D screens idea, I also don't have any of those..

**Comment by joshbux** [comment] 2015-11-03 20:43
I have 3d monitors, but no glasses. I'll do some experimentation with the
settings when I get home.

Again, @falahati, I'm guessing you just want to save the user's preference
for extended mode and use that.

Josh

**Comment by falahati** [comment] 2015-11-03 20:53
Lets hope not :) Because doing so need a lot of changes in the program.

And I dont really think that this "3D" has the same meaning as "Stereoscopic 3D" settings. I believe this one means 3D Rendering, like games and 3D applications.
As far as I know, "Stereoscopic 3D" has a completely different tree node in the nVidia Control Panel and has nothing to do with Surround and SLI.

I really need to know:
1) What actually the first option does? 
2) If by switching to the first option, you get only one active monitor, can you enable other monitors using the Win+P buttons and choosing the "Extended Mode"?

**Comment by falahati** [comment] 2015-11-03 20:56
3) What happens when you are in extended mode and want to enable Surround mode without clicking "Configure" button? (Select second option and then Apply button right away)
Does it still ask you to close some specific programs? (Chrome and Firefox for example)

**Comment by ZaLiTHkA** [comment] 2015-11-03 21:51
I just ran a few tests quickly, and here's a quick breakdown from my setup:
1. "Maximise 3D performance": Enables SLI, each monitor reported individually, full screen apps go to the first monitor (see caveats below).
2. "Surround": Enables SLI, all monitors reported as one, full screen apps go to the only monitor Windows sees (5760x1080).
3. "Activate all displays": (disabled, so I can't check it)
4. "Disable SLI": Disables SLI, each monitor reported individually, didn't bother to check any full screen apps (aka: games).

Meh... Well this sucks. :/ Here are a couple annoying caveats to keep in mind:
- Switching from "Surround" to either "Maximise 3D Performance" or "Disable SLI" only enables the first monitor. Additional monitors must be manually enabled in the "Set up multiple displays" control panel page.
- After enabling the additional displays, ~~they revert to a numerical order of `[ 1 ][ 2 ][ 3 ]`~~ [edit] the first is already enabled and extra displays get added to the right in the order they're enabled, regardless of previous settings. My physical setup has them arranged as `[ 2 ][ 1 ][ 3 ]`, which means switching to individual monitors involves:
  - Select 3D
  - Enable extra displays
  - Rearrange displays

As for apps it needs to close first, in addition to Chrome and Firefox, it also makes me close my Thermaltake water loop "Fan Control Software". Not sure if it affects other desktop apps since I normally clear my desktop before I change this, but I can only imagine it's looking for apps that use a specific type of window rendering, since the only commonality I can see between these apps is that they have custom window frames.

Suddenly this doesn't appear to be too simple to automate anymore...

**Comment by falahati** [comment] 2015-11-03 23:15
Thanks for detailed information.
About the notes: We are actually doing that already. So no need to change anything there. Its alright.

Based on the information you provided I am going to save the SLI status (Enable - Disable) and select the 4th and 1st options accordingly (Fallback to 3rd option if 1st one is disable) for extended mode. And for Surround mode I do as before but using the 2nd radio button instead of the Checkbox.

Then I try to restore the monitor settings after switching to extended or surround mode.

**Comment by joshbux** [comment] 2015-11-04 04:36
OK so I finally got around to a little bit of experimenting. When I
selected surround, it actually automatically selected Maximize 3D
 performance after it switched, so that clearly works in surround mode. So
I couldn't select that to turn surround off - I had to use option 3
(Activate all displays). That actually turned all 3 on instead of only 1 so
I didn't need to use Windows+P, but it didn't save my monitor
configuration.

I'll have to do more experimentation later - my CPU cooler's pump hasn't
been working since I got it so my CPU is severely throttling itself and
every now and then it just hangs. Will hopefully get more info when I'm at
full power.

**Comment by BradB111** [comment] 2016-02-08 11:56
Is this issue resolved? I have an sli setup very similar to those above and was wondering if i could help at all with trying to resolve this issue. I would love to use the program if at all possible.

current sli setup:
2x 980Ti 
3x 1080p monitors

**Comment by drew173** [comment] 2016-02-09 22:12
Hi -
The issue here, as near as I can tell, has to do with (or at least starts with) the difference in UI between SLI and non-SLI configurations.  I've attached screenshot examples of what each looks like below.

In Surround.cs, you've got the following around line 395:
`surroundCheckbox = window.GetChildWindowWithControlId<CheckBox>(1866);
                        return surroundCheckbox != null;
                    });
                if (surroundCheckbox == null)
                {
                    throw new Exception(Language.Surround_Can_t_find_the_surround_settings_);
                }`

As you can see from the SLI screenshot, it's not a checkbox for an SLI configuration - it's a radio button.  The ControlId of the radio button according to the VisualUIAutomation tool is **1864** - not 1866 like the checkbox is in the code.  

The tool lists it as:  "button" "Span displays with Surround" "1864"

And this is therefore returning the "Can't find the surround settings" exception on line 400, because surroundCheckbox is null, because there is no control ID 1866 for SLI configs; it's a button with ID 1864.

Fixing and recompiling this is beyond me, though.  @falahati if this is enough for you to maybe try fixing this, awesome.  I would looooooooooove to be able to use this app, hell, I'll donate $20 to you.  If not, hey, no worries, and thanks for trying.

Here are those screenshots: 

non-SLI:
![non-sli](https://cloud.githubusercontent.com/assets/3639812/12932072/d90d7f58-cf35-11e5-8218-0a912087db50.gif)

SLI:
![sli](https://cloud.githubusercontent.com/assets/3639812/12932090/eaee1db8-cf35-11e5-96fd-7934fcfce2c0.gif)

**Comment by falahati** [comment] 2016-02-10 09:14
Unfortunately, not yet. I was and am little busy since couple of weeks ago and didn't managed to find some free time to implement the changes. I will try to provide a beta version of the program for SLI users in the next 10 days, give or take a few.

**Comment by alexmaurizio** [comment] 2016-02-26 18:05
I think i'll try to fork and fix the bugs for the SLI/Surround version. I'll also make the version in Italian for me and i'll probably try to figure out some multi-language issue.

As of now I have the problem "couldn't find windows with title" and then i'll probably have the surround problem. I'll probably need some more step to re-enable all the monitors after switching back (while in SLI).

Ah, for anyone wondering, there are 4 MODES:

1) Optimise 3D (SLI mode + 3 single res monitors)
2) Surround (SLI mode + Single Big Surround monitor)
3) Activate all screens (This works ONLY if you connect some monitors to first card and others to second one - it DISABLES SLI, because in SLI-MODE you can connect monitors only to ONE card. This is why it's grey for you who have - rightfully - connected them all to the main card)
4) Disable SLI (disables monitor on second card, disables SLI - it sucks.)

The switching sequence for a correct SLI + 3 monitors setup would be:
1) Switch from "OPTIMIZE 3D" to "SURROUND"
2) do stuff

On back, it's

1) Switch from "SURROUND" to "OPTIMIZE 3D"
2) RE-ENABLE MONITORS in the second panel 
3) do stuff

i don't know how the program works since I can't run as of now, but I appreciate all your work.

On my way to try to do something. if I will succeed, i'll post back. :)

**Comment by Tomblarom** [comment] 2016-03-07 12:14
Hey guys! Are still working on it? I'm also using SLI.

**Comment by PeterFragon** [comment] 2016-05-04 23:24
I am also using SLI and am willing to offer some help if I can,I want this to work so bad! I would even be willing to do some remote sessions with you @falahati if you need access to a machine with SLI running..

**Comment by alexmaurizio** [comment] 2016-05-04 23:30
No problem mate, just help if you want to :) I'm totally busy with work now and can't go on with this for now. Look at my fork to start :)

PS: I suggest using DesktopOK 64bit to refresh icon to original positions after manual switch between Surround and Tri-Single SLI, works like a charm on Windows 10 64bit :)

**Comment by PeterFragon** [comment] 2016-05-04 23:42
I use stardock fences for that and rain meter..

**Comment by falahati** [comment] 2016-05-11 22:16
Hi @PeterFragon , I really do like the remote thing idea :) It would certainly help. Add me on Skype: s_falahati

**Comment by PeterFragon** [comment] 2016-05-16 23:46
Added ..

**Comment by falahati** [comment] 2016-05-21 18:13
Meanwhile, I just tried to add the SLI functionality to the app, if any one can test the code, it would be great. Just compile the project under 'sli-beta' branch.

**Comment by BradB111** [comment] 2016-05-21 18:18
No idea how to compile.... but willing to test. Also Nvidia's latest update allows the built in hotkey to be used and it remembers the surround config, just not the previous config so you are still required to enable the other monitors and then reposition and then for me set refresh rate to 144

but enabling surround is easier now at least.

**Comment by brice-ruppen** [comment] 2016-10-17 12:18
Hi, I just tested last update, but it does not work.
It's failing at : surroundRadioButton?.IsSelected
TestStack.White does not see when it is checked.

My first guess would be that it is not a Radio Button, just a custom Button.
![image](https://cloud.githubusercontent.com/assets/5494542/19437162/75561c68-9474-11e6-8901-181af0755447.png)

**Comment by falahati** [comment] 2017-02-16 00:06
I will take a look at this.

**Comment by ZaLiTHkA** [comment] 2017-02-16 06:21
@falahati, major respect for not giving up on this project... It must be a bit task trying to cater for so many different configurations.

For what it's worth, I now dual boot my system at home, using Windows for games and PhotoShop, but Linux for everything else. So even though I don't have any need to constantly switch Surround on and off, I'm still available to help test things if you need.. Just ping me here on GitHub and I'll do what I can. :)

**Comment by falahati** [comment] 2017-02-16 09:34
@ZaLiTHkA, Thanks

Meanwhile, can you check out the newly fixed (at last) hotkeys for surround settings? Does it work with SLI setups?
It is in right bottom corner of surround settings page (NVidia Control Panel). I may switch to this method for surround toggling if it works with SLI flawlessly.

**Comment by falahati** [comment] 2017-02-16 11:25
@ZaLiTHkA,

If you managed to do that, it would be great if you could also send me a backup of your registry from this address, while surround is active.

> HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\Global\Persistence\Surround

Please send it to my email address at [s_falahati@hotmail.com](mailto:s_falahati@hotmail.com)

Thanks

**Comment by ZaLiTHkA** [comment] 2017-02-17 06:30
No problem, I'll check that out when I get home this evening.

**Comment by ZaLiTHkA** [comment] 2017-02-23 20:38
Sorry about the delay, between weather issues threatening to flood my house and me having recently broke a few things in my Windows installation, I haven't had time to do much with my PC lately.. I'll get back to this as soon as I can get back into Windows again.

**Comment by falahati** [comment] 2017-02-23 21:58
@ZaLiTHkA, Thanks. but there is no need for that information anymore. Expect a new version of this application, probably with another name and repository, this time supporting multiple profiles and using NvAPI instead of UI manipulation, in next few weeks.

I am going to notify all and then close this issue as soon as the other project becomes public.

**Comment by falahati** [comment] 2017-03-29 23:15
Hi again guys,

I made a pre-release for the next version of this program; anyone here interested in giving it a try? It does lack some of the features of this program like context menu and shortcut generation at this point, but it will have them before public release.

Please contact me to provide you with a sample executable file, so you can test the new release, especially if you have an SLI setup. I really do like to know if it works flawlessly with SLI setups.

Skype and Email: s_falahati@hotmail.com

**Comment by PeterFragon** [comment] 2017-05-20 02:47
I have SLI still send to me

**Comment by PeterFragon** [comment] 2017-05-20 02:52
@falahati We should work out a time for me to give you TeamViewer access to my machine to work on an SLI solution..

**Comment by falahati** [comment] 2017-05-20 11:38
@PeterFragon 
Hey Peter,

Please check the file I shared on this issue:

https://github.com/falahati/NVIDIASurroundToggler/issues/21

**Comment by falahati** [comment] 2017-08-10 14:32
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.

**Closed as completed by falahati** 2017-08-10 14:32 UTC
