### ISSUE TITLE
NTH one step more needet

### ISSUE THREAD

**Issue by Xanadou** [falahati/NVIDIASurroundToggler#13] opened 2016-09-05 11:11 UTC
Hello,

at first, this is a very nice tool. Thanks for it.

Now my whishes: When I configure the surround, I take my 3 monitors and set the bezel correcture. Then I can push the "create surround" button. Now I need another step to set the resolution bezel corrected. 
Is this possible or can you implement this? (btw I have the german nvidia 372.70 version)

Best regards
Xanadou

**Comment by falahati** [comment] 2016-09-05 15:01
Hey man, I didn't understand the question. What setting you want to set exactly?

**Comment by Xanadou** [comment] 2016-09-05 15:42
Hello,

I take a screen: http://its-maassen.de/share/nvidia.jpg

The last step is to switch from 5760x1080 to 6050x1080

the usual way -> activate surround. Then set the bezel correcture to 145. Then click accept and at last change the resolution to 6050x1080 and accept again.

I hope it was understandable

Best regards
Xanadou

**Comment by falahati** [comment] 2016-09-05 17:31
Well, it should be able to do all of this, especially​ resolution. Bazell was a problem in the last release but got fixed in latest one (today).

**Comment by Xanadou** [comment] 2016-09-05 19:27
thx for support. But I´m not able to select the resolution. When I want to select the new resulotion the windows shortly freeze and than I have no time to select. I see the dropdown but I´m not fast enough to select enything

**Comment by falahati** [comment] 2016-09-05 19:42
I see, the problem is that you first need to apply the settings and then select the resolution. This only happens if you want to apply a bezel specific resolution, correct? Well my tool will close the form as soon as it find your settings applied. So this is not possible now.
The other way around this is to ask for resolution later on in another form. Will try that to see if I can put in inside code for next release.

**Comment by Xanadou** [comment] 2016-09-05 20:02
Yes, this is correct. 
I would be happy to see this function in the next release. :+1: 
thx.

Best regards
Xanadou

**Comment by Xanadou** [comment] 2016-09-05 21:34
>  Well my tool will close the form as soon as it find your settings applied.

Why? Isn´t it possible to wait and configure the resulution and then close? The nvida setup do so.

**Comment by falahati** [comment] 2017-08-10 14:34
The new project is located here:
https://github.com/falahati/HeliosDisplayManagement/

This issue is now closed, please create a new issue at the new project's issue tracker if you had any problem with it.

**Closed as completed by falahati** 2017-08-10 14:34 UTC
Labels: enhancement
